version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: lang-match-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lang-match
    volumes:
      - mongodb_data:/data/db
    networks:
      - lang-match-network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lang-match-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/lang-match?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - mongodb
    networks:
      - lang-match-network

  # App Móvil
  mobile:
    build:
      context: ./frontend/mobile
      dockerfile: Dockerfile
    container_name: lang-match-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_SOCKET_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - lang-match-network

  # Dashboard
  dashboard:
    build:
      context: ./frontend/dashboard
      dockerfile: Dockerfile
    container_name: lang-match-dashboard
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - lang-match-network

volumes:
  mongodb_data:

networks:
  lang-match-network:
    driver: bridge
